const productsData = [
    {
        id: 101,
        name: "Smartphone X",
        description: "A powerful smartphone with cutting-edge features.",
        price: 599.99,
        quantity: 100,
        brandName: "TechMaster",
        image: "https://m.media-amazon.com/images/I/412XtEOcI9S._MCnd_AC_.jpg",
        reviews: [
          {
            id: 201,
            user_id: 301,
            username: "reviewer_1",
            rating: 4,
            comment: "Great product! Highly recommended.",
            created_at: "2023-08-04T10:15:30Z",
          },
          {
            id: 202,
            user_id: 302,
            username: "reviewer_2",
            rating: 5,
            comment: "I love this phone! Best purchase ever.",
            created_at: "2023-08-03T15:22:45Z",
          },
        ],
      },
      {
        id: 102,
        name: "Wireless Headphones",
        description: "High-fidelity wireless headphones for an immersive audio experience.",
        price: 129.99,
        quantity: 50,
        brandName: "AudioZen",
        image: "https://m.media-amazon.com/images/I/412XtEOcI9S._MCnd_AC_.jpg",
        reviews: [
          {
            id: 203,
            user_id: 303,
            username: "reviewer_3",
            rating: 5,
            comment: "Excellent sound quality! I'm impressed.",
            created_at: "2023-08-04T09:30:00Z",
          },
          {
            id: 204,
            user_id: 304,
            username: "reviewer_4",
            rating: 4,
            comment: "Great value for money.",
            created_at: "2023-08-03T14:40:20Z",
          },
        ],
      },
      {
        id: 103,
        name: "Ultra HD Smart TV",
        description: "A 65-inch ultra-high-definition smart TV with built-in streaming apps.",
        price: 899.00,
        quantity: 30,
        brandName: "VisionTech",
        image: "https://m.media-amazon.com/images/I/412XtEOcI9S._MCnd_AC_.jpg",
        reviews: [
          {
            id: 205,
            user_id: 305,
            username: "reviewer_5",
            rating: 4,
            comment: "Impressive picture quality. Loving it!",
            created_at: "2023-08-02T12:18:10Z",
          },
          {
            id: 206,
            user_id: 306,
            username: "reviewer_6",
            rating: 5,
            comment: "This TV exceeded my expectations!",
            created_at: "2023-08-01T17:05:55Z",
          },
        ],
      },
      {
        id: 104,
        name: "Gaming Laptop",
        description: "A gaming powerhouse with top-of-the-line graphics and processing.",
        price: 1499.99,
        quantity: 20,
        brandName: "GameRig",
        image: "https://m.media-amazon.com/images/I/412XtEOcI9S._MCnd_AC_.jpg",
        reviews: [
          {
            id: 207,
            user_id: 307,
            username: "reviewer_7",
            rating: 5,
            comment: "Amazing performance! Perfect for gaming.",
            created_at: "2023-07-31T08:40:45Z",
          },
          {
            id: 208,
            user_id: 308,
            username: "reviewer_8",
            rating: 4,
            comment: "Highly recommended for gamers.",
            created_at: "2023-07-30T14:30:30Z",
          },
        ],
      },
      {
        id: 105,
        name: "Wireless Earbuds",
        description: "Sleek and lightweight earbuds with noise-canceling technology.",
        price: 79.99,
        quantity: 100,
        brandName: "SoundPod",
        image: "https://m.media-amazon.com/images/I/412XtEOcI9S._MCnd_AC_.jpg",
        reviews: [
          {
            id: 209,
            user_id: 309,
            username: "reviewer_9",
            rating: 4,
            comment: "Clear sound and comfortable fit.",
            created_at: "2023-07-29T19:20:15Z",
          },
          {
            id: 210,
            user_id: 310,
            username: "reviewer_10",
            rating: 5,
            comment: "No regrets purchasing these earbuds.",
            created_at: "2023-07-28T11:12:00Z",
          },
        ],
      },
      {
        id: 106,
        name: "Fitness Tracker",
        description: "Track your health and fitness goals with this advanced wearable.",
        price: 49.95,
        quantity: 150,
        brandName: "FitLife",
        image: "https://m.media-amazon.com/images/I/412XtEOcI9S._MCnd_AC_.jpg",
        reviews: [
          {
            id: 211,
            user_id: 311,
            username: "reviewer_11",
            rating: 5,
            comment: "Very accurate and easy to use.",
            created_at: "2023-07-27T16:48:30Z",
          },
          {
            id: 212,
            user_id: 312,
            username: "reviewer_12",
            rating: 4,
            comment: "Helped me stay motivated on my fitness journey.",
            created_at: "2023-07-26T09:25:50Z",
          },
        ],
      },
      {
        id: 107,
        name: "Professional Camera",
        description: "Capture stunning images and videos with this high-end DSLR camera.",
        price: 1799.00,
        quantity: 10,
        brandName: "PhotoPro",
        image: "https://m.media-amazon.com/images/I/412XtEOcI9S._MCnd_AC_.jpg",
        reviews: [
          {
            id: 213,
            user_id: 313,
            username: "reviewer_13",
            rating: 4,
            comment: "Great camera for professional photography.",
            created_at: "2023-07-25T15:10:40Z",
          },
          {
            id: 214,
            user_id: 314,
            username: "reviewer_14",
            rating: 5,
            comment: "Amazing video quality. Highly recommended for filmmakers.",
            created_at: "2023-07-24T12:30:15Z",
          },
        ],
      },
      {
        id: 108,
        name: "Stylish Watch",
        description: "A sleek and elegant watch for every occasion.",
        price: 249.50,
        quantity: 75,
        brandName: "TimeTrend",
        image: "https://m.media-amazon.com/images/I/412XtEOcI9S._MCnd_AC_.jpg",
        reviews: [
          {
            id: 215,
            user_id: 315,
            username:
            "reviewer_15",
            rating: 5,
            comment: "Classy design and excellent build quality.",
            created_at: "2023-07-23T08:55:10Z",
          },
          {
            id: 216,
            user_id: 316,
            username: "reviewer_16",
            rating: 4,
            comment: "Great value for a stylish watch.",
            created_at: "2023-07-22T17:40:25Z",
          },
        ],
      },
      {
        id: 109,
        name: "Premium Coffee Maker",
        description: "Brew the perfect cup of coffee with this feature-rich coffee maker.",
        price: 89.99,
        quantity: 40,
        brandName: "CafeMatic",
        image: "https://m.media-amazon.com/images/I/412XtEOcI9S._MCnd_AC_.jpg",
        reviews: [
          {
            id: 217,
            user_id: 317,
            username: "reviewer_17",
            rating: 4,
            comment: "Makes delicious coffee. A must-have for coffee enthusiasts.",
            created_at: "2023-07-21T12:20:30Z",
          },
          {
            id: 218,
            user_id: 318,
            username: "reviewer_18",
            rating: 5,
            comment: "Best coffee maker I've ever owned.",
            created_at: "2023-07-20T09:15:00Z",
          },
        ],
      },
      {
        id: 110,
        name: "Ultrabook",
        description: "An ultra-slim and lightweight laptop for productivity on-the-go.",
        price: 1199.00,
        quantity: 25,
        brandName: "SwiftBook",
        image: "https://m.media-amazon.com/images/I/412XtEOcI9S._MCnd_AC_.jpg",
        reviews: [
          {
            id: 219,
            user_id: 319,
            username: "reviewer_19",
            rating: 5,
            comment: "Super fast and portable. Ideal for travel.",
            created_at: "2023-07-19T16:05:40Z",
          },
          {
            id: 220,
            user_id: 320,
            username: "reviewer_20",
            rating: 4,
            comment: "Good battery life and sleek design.",
            created_at: "2023-07-18T11:30:20Z",
          },
        ],
      },
]

module.exports = productsData